# Generated by Django 5.1.4 on 2025-01-03 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bookinstance_borrower_alter_bookinstance_imprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_view_all_book_instance_on_loan', 'view'),)},
        ),
    ]
